 - name: build and run the docker container
  hosts: localhost
  tasks:
    - name: Install pip
      apt: name=python-pip state=present

    - name: install docker-py
      pip: name=docker-py

    - name: Creating the container
      docker_container:
        name: hello-node-dev
        image: localhost:5000/hello-node:latest
        state: present

    - name: Running the container
      docker_container:
        name: hello-node-dev
        published_ports:
          - "3004:3000"
        image: localhost:5000/hello-node:latest
        state: started
