- name: build and run the docker container
  hosts: localhost
  tasks:
    - name: Install pip
      apt: name=python-pip state=present

    - name: install docker-py
      pip: name=docker-py

    - name: Build Docker image from Dockerfile
      docker_image:
        name: hello-node
        build:
          path: .
        source: build

    - name: Running the container
      docker_container:
        name: hello-node-app
        image: hello-node:latest
        state: running
